config/routes.rb
AwsSimpleDbTool::Application.routes.draw do

  match 'login_post'	=>	'welcome_page#login_post'
  match 'logout'		=>	'welcome_page#logout'

  match 'about'			=>	'welcome_page#about'

  resource :sdb_domains

  root :to => "welcome_page#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery

end

app/controllers/sdb_domains_controller.rb
class SdbDomainsController < ApplicationController

	include AwsSdbHelper

	def show

		init_sdb_from_session(session)

		@sdb_domains = @sdb.list_domains


	end


end

app/controllers/welcome_page_controller.rb
require "sdb/right_sdb_interface"


class WelcomePageController < ApplicationController

	include AwsSdbHelper


	def index
		if session.has_key?(:aws_access_key) and session.has_key?(:aws_secret_key)
#			redirect_to about_path

		end
	end



	def about
		@title = 'About'
	end




	def login_post
		aws_access_key = params[:login_form][:aws_access_key]
		aws_secret_key = params[:login_form][:aws_secret_key]

		begin

			init_sdb(aws_access_key, aws_secret_key)

			session[:aws_access_key] = aws_access_key
			session[:aws_secret_key] = aws_secret_key

			sdb_domains = @sdb.list_domains

			redirect_to sdb_domains_path

		rescue Exception => e

			flash.now[:error] = "Invalid AWS credentials: " + e.to_s


			session.clear

			render 'index'

		end
	end




	def logout
		session.clear
		redirect_to :root
	end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_html_title

    base_title = "Amazon SimpleDB WebUI"

    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end

  end

  
end

app/helpers/aws_sdb_helper.rb
module AwsSdbHelper

	def init_sdb(aws_access_key, aws_secret_key)
		@sdb = RightAws::SdbInterface.new(aws_access_key, aws_secret_key,
										  {
												  :api_version => '2009-04-15'
										  })
	end


	def init_sdb_from_session(session)
		init_sdb(session[:aws_access_key], session[:aws_secret_key])
	end
end

app/helpers/sdb_domains_helper.rb
module SdbDomainsHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/layouts/_logout.html.erb
<li><%= link_to "Logout", logout_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
		"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
	<title><%= page_html_title %></title>


	<link rel="stylesheet" media="print" href="http://github.com/joshuaclayton/blueprint-css/raw/master/blueprint/print.css" type="text/css"/>
	<link rel="stylesheet" media="screen" href="http://github.com/joshuaclayton/blueprint-css/raw/master/blueprint/screen.css" type="text/css"/>
	<!--[if lt IE 8]>
	<link rel="stylesheet" media="screen"
		  href="http://github.com/joshuaclayton/blueprint-css/raw/master/blueprint/ie.css" type="text/css"/>
	<![endif]-->
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>

	<%= javascript_include_tag :defaults %>

	<%= csrf_meta_tag %>
</head>


<body>

<div class="container">

	<header>
		<% logo = image_tag("logo.png", :alt => "Amazon SimpleDB WebUI logo", :class => "round") %>
		<%= link_to logo, root_path %>
		<nav class="round">
			<ul>
				<li><%= link_to "About", about_path %></li>
				<!--
				<li><%= link_to "Donate", '#' %></li>
				-->
				<%= render 'layouts/logout' if session.has_key?(:aws_access_key) %>
			</ul>
		</nav>
	</header>

	<section class="round">

		<%= yield %>

	</section>



</div>

<hr />

<%= debug(params) if Rails.env.development? %>

<hr />

<%= debug(session) if Rails.env.development? %>


</body>

</html>

app/views/sdb_domains/show.html.erb
<%= debug(@sdb_domains)  %>

app/views/welcome_page/about.html.erb
<h1>About</h1>
<p>created to help you take a better look at the data you're storing
  in <a href="http://aws.amazon.com/simpledb" target="_blank">Amazon SimpleDB</a></p>

app/views/welcome_page/index.html.erb
<h1>Welcome to Amazon SimpleDB WebUI</h1>
<p>created to help you take a better look at the data you're storing
	in <a href="http://aws.amazon.com/simpledb" target="_blank">Amazon SimpleDB</a></p>



<%= form_for(:login_form , :url => login_post_path) do |form| %>

	<% flash.each do |key, value| %>
	  <div class="flash <%= key %>"><%= value %></div>
	<% end %>


	<table border="0" cellpadding="2" cellspacing="2" class="login_table">
		<tr>
			<td><%= form.label :aws_access_key %></td>
			<td><%= form.text_field :aws_access_key %></td>
		</tr>

		<tr>
			<td><%= form.label :aws_secret_key %></td>
			<td><%= form.password_field :aws_secret_key %></td>
		</tr>
	</table>


	<div class="actions">
		<%= form.submit "Login" %>
	</div>

<% end %>

app/views/welcome_page/login_post.html.erb
login_post